# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
      - run:
          name: Build
          command: |
            # Init Get SemVer from Circle CI Environment Variables (Github https://github.com/vikadata/devops/blob/main/scripts/semver_ci/semver_ci.sh)
            eval "$(curl -fsSL -H 'Authorization: token '"$CR_PAT" https://raw.githubusercontent.com/vikadata/devops/main/scripts/semver_ci/semver_ci.sh)"

            build_docker_dotversion caddy

filters: &filters
  branches:
    only:
      - alpha
  tags:
    only: /^v.*/

workflows:
  default:
    jobs:
      - build:
          filters: *filters
